server:
  port: 8010

base:
  config:
    nacos:
      hostname: 192.168.1.117
      port: 8848
    seata:
      hostname: 192.168.1.117
      port: 8091

spring:
  application:
    name: biz-service
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.117:3306/seatatest?useUnicode=true&characterEncoding=utf-8&useSSL=false&useInformationSchema=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhichao.dida.domain

mapper:
  mappers: tk.mybatis.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

feign:
  httpclient:
    enabled: true
  sentinel:
    enabled: true

seata:
  application-id: ${spring.application.name}
  tx-service-group: default
  service:
    vgroupMapping:
      default: default
    grouplist:
      default: ${base.config.seata.hostname}:${base.config.seata.port}
